# Generated by Django 5.2.5 on 2025-08-28 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
        migrations.AlterField(
            model_name='voucher',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=models.IntegerField(help_text='Enter a percentage value between 0 and 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
